# HQ MIR ID Controller API Service Deployment definition
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mirid-controller
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: mirid-controller
            deployment: hq
    replicas: 1
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: mirid-controller
                deployment: hq
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                              - key: iorg-node-reliability
                                operator: In
                                values:
                                - stable
                podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 50
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: environment
                          operator: In
                          values:
                          - production
                        - key: tier
                          operator: In
                          values:
                          - api
                        - key: app
                          operator: In
                          values:
                          - mirid-controller
                        - key: deployment
                          operator: In
                          values:
                          - hq
                      topologyKey: "kubernetes.io/hostname"
            containers:
                - name: cloud-hq-ws-mirid-controller
                  image: identifiersorg/cloud-hq-ws-mirid-controller:1.0.0
                  resources:
                      requests:
                          memory: 420Mi
                          cpu: 100m
                  env:
                  - name: HQ_WS_MIRID_CONTROLLER_JVM_MEMORY_MAX
                    value: "420m"
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_APPLICATION_ACTIVE_PROFILE
                    value: "authenabled"
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_JDBC_URL
                    value: "jdbc:postgresql://hq-postgresql:5432/dbhqmiridcontroller"
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_USERNAME
                    valueFrom:
                        secretKeyRef:
                            name: hq-mirid-controller-database-credentials
                            key: username
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: hq-mirid-controller-database-credentials
                            key: password
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_HOST
                    value: "redis"
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_PORT
                    value: "6379"
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI
                    value: "https://auth.identifiers.org/auth/realms/idorg/"
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID
                    valueFrom:
                        secretKeyRef:
                            name: hq-mirid-controller-keycloak-credentials
                            key: clientid
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET
                    valueFrom:
                        secretKeyRef:
                            name: hq-mirid-controller-keycloak-credentials
                            key: clientsecret
                  - name: HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
                    value: "https://auth.identifiers.org/auth/realms/idorg"
                  ports:
                  - containerPort: 8181
                  readinessProbe:
                      httpGet:
                          path: /healthApi/readiness_check
                          port: 8181
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  livenessProbe:
                      httpGet:
                          path: /healthApi/liveness_check
                          port: 8181
                      initialDelaySeconds: 90
                      periodSeconds: 10
