# HQ deployment Ingress resource for global load balancing
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hq-deployment
  labels:
    environment: production
    tier: api
    app: hq-deployment
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: idorg-staging
    ingress.gcp.kubernetes.io/pre-shared-cert: 'cert-iorg-hq-production-web,cert-iorg-hq-production-auth,cert-iorg-hq-production-api-registry,cert-iorg-hq-production-api-mirid,idorg-test-echo'
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    # Registry API rules
    - host: registry.api.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-registry
              port:
                number: 8180
          pathType: ImplementationSpecific
    # MIR ID Controller API Service rules
    - host: mirid.api.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-mirid-controller
              port:
                number: 8181
          pathType: ImplementationSpecific
    # Registry Web Frontend rules
    - host: registry.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-web-hq
              port:
                number: 80
          pathType: ImplementationSpecific
    # Accounts web
    - host: auth.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-keycloak
              port:
                number: 8080
          pathType: ImplementationSpecific
    # Testing endpoint
    - host: echo.identifiers.org
      http:
        paths:
        - backend:
            service:
              name: nodeport-nginx-echo-headers
              port:
                number: 8080
          pathType: ImplementationSpecific
