# HQ MIR ID Controller Service (node port based internal load balancer)
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: nodeport-mirid-controller
    labels:
        environment: production
        tier: api
        app: mirid-controller
        deployment: hq
spec:
    ports:
    - port: 8181
    selector:
        environment: production
        tier: api
        app: mirid-controller
        deployment: hq
    type: NodePort
