# Definition for a keycloak service (node port based load balancing)
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: nodeport-keycloak
    annotations:
        cloud.google.com/neg: '{"ingress": true}'
    labels:
        environment: production
        tier: backend
        app: keycloak
        deployment: hq
spec:
    ports:
    - port: 8080
    selector:
        environment: production
        tier: backend
        app: keycloak
        deployment: hq
    type: NodePort
